import type { Metadata } from "next";
import { Inter } from "next/font/google";

import 'aos/dist/aos.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Malicul Home",
  description: "Generated by create next app",
  icons: {
    icon: '/icon.png', // /public path
  },
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} leading-normal tracking-normal text-white gradient`}>{children}</body>
    </html>
  );
}
