import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";

import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const footerSections = [
    {
      title: 'Links',
      links: [
        { title: 'FAQ', url: '#' },
        { title: 'Help', url: '#' },
        { title: 'Support', url: '#' },
      ],
    },
    {
      title: 'Legal',
      links: [
        { title: 'Terms', url: '#' },
        { title: 'Privacy', url: '#' },
      ],
    },
    {
      title: 'Social',
      links: [
        { title: 'Facebook', url: '#' },
        { title: 'Linkedin', url: '#' },
        { title: 'Twitter', url: '#' },
      ],
    },
    {
      title: 'Company',
      links: [
        { title: 'Official Blog', url: '#' },
        { title: 'About Us', url: '#' },
        { title: 'Contact', url: '#' },
      ],
    },
  ];
  return (
    <html lang="en">
      <body className={`${inter.className} leading-normal tracking-normal text-white gradient`}>
      <Navbar />
        {children}</body>
        <Footer sections={footerSections} />
    </html>
  );
}
